/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gamedoanso;

/**
 *
 * @author tranv
 */
public class ItemDoanSo extends javax.swing.JPanel {

    /**
     * Creates new form ItemDoanSo
     */
    public ItemDoanSo(int stt, String soDoan, int soDung, int viTriDung) {
        initComponents();
        
        lbStt.setText(String.valueOf(stt));
        lbSoDoan.setText(soDoan);
        lbSoDung.setText(String.valueOf(soDung));
        lbViTriDung.setText(String.valueOf(viTriDung));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbStt = new javax.swing.JLabel();
        lbSoDoan = new javax.swing.JLabel();
        lbViTriDung = new javax.swing.JLabel();
        lbSoDung = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 32));

        lbStt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbStt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStt.setText("1");

        lbSoDoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSoDoan.setText("1234");

        lbViTriDung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbViTriDung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbViTriDung.setText("3");

        lbSoDung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSoDung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSoDung.setText("3");
        lbSoDung.setPreferredSize(new java.awt.Dimension(45, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbStt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSoDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(lbSoDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbViTriDung, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStt)
                    .addComponent(lbSoDoan)
                    .addComponent(lbViTriDung)
                    .addComponent(lbSoDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbSoDoan;
    private javax.swing.JLabel lbSoDung;
    private javax.swing.JLabel lbStt;
    private javax.swing.JLabel lbViTriDung;
    // End of variables declaration//GEN-END:variables
}
