/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gamedoanso;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tranv
 */
public class TrangChu extends javax.swing.JFrame {

    final int soLanDoanToiDa = 10;
    private int soLanDoan = 0;
    private ArrayList<Integer> ketQua;
    private ArrayList<Integer> arrSoNhap = new ArrayList<>();

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(10);

        //test
//        for (int i = 0; i < 6; i++) {
//            JPanel pn = new ItemDoanSo();
//            pnListSoDoan.add(pn);
//        }
        //set event
        setEvent();

        //reset tro choi
        resetTroChoi();
    }

    public void randomKetQua() {
        ArrayList<Integer> numbers = new ArrayList<>();
        for (int i = 1; i <= 9; i++) {
            numbers.add(i);
        }
        Collections.shuffle(numbers); // Trộn ngẫu nhiên các số
        ArrayList<Integer> result = new ArrayList<>(numbers.subList(0, 4)); // Lấy 4 số đầu tiên
        ketQua = result;
    }

    public void setEvent() {
        tfNhapSo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == 8) {
                    if (!arrSoNhap.isEmpty()) {
                        arrSoNhap.removeLast();
                    }
                    tfNhapSo.setEditable(true);
                }
                else if (e.getKeyCode() > 48 && e.getKeyCode() <= 57) {

                    int so = Integer.parseInt(String.valueOf(e.getKeyChar()));
                    int kq = arrSoNhap.indexOf(so);
                    if (kq == -1 && arrSoNhap.size() <= 4) {
                        arrSoNhap.add(so);
                        tfNhapSo.setEditable(true);
                    } else {
                        tfNhapSo.setEditable(false);
                    }

                }  else {
                    tfNhapSo.setEditable(false);
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnChoiLại = new javax.swing.JButton();
        tfNhapSo = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnGoiY = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnListSoDoan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taGhiChu = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        tfGhiChu1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfGhiChu2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfGhiChu3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfGhiChu4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(690, 620));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Game Đoán Số");

        btnChoiLại.setText("Chơi lại");
        btnChoiLại.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoiLạiActionPerformed(evt);
            }
        });

        tfNhapSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNhapSoActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.setFocusPainted(false);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnGoiY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon-question.png"))); // NOI18N
        btnGoiY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoiY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoiYMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STT");

        jLabel3.setText("Số đoán");

        jLabel4.setText("Vị trí đúng");

        jLabel5.setText("Số đúng");

        jScrollPane1.setBorder(null);

        pnListSoDoan.setLayout(new javax.swing.BoxLayout(pnListSoDoan, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(pnListSoDoan);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ghi chú");

        taGhiChu.setColumns(20);
        taGhiChu.setLineWrap(true);
        taGhiChu.setRows(5);
        taGhiChu.setWrapStyleWord(true);
        taGhiChu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(taGhiChu);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("1");

        tfGhiChu1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("2");

        tfGhiChu2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("3");

        tfGhiChu3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("4");

        tfGhiChu4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfGhiChu2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfGhiChu3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfGhiChu4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGhiChu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGhiChu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGhiChu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfNhapSo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGoiY)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnChoiLại))
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnChoiLại)
                            .addComponent(btnOK)
                            .addComponent(tfNhapSo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGoiY, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoiYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoiYMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Trò chơi yêu cầu người chơi chọn đúng số có 4 chứ số khác nhau từ 1-9 không bao gồm số 0.\n"
                + " Người chơi có " + soLanDoanToiDa + " lần đoán, mỗi lần dự đoán hệ thống sẽ đưa ra 2 gợi ý, 1 là số lượng chữ số đã đoán đúng, 2 là số lượng chữ số đúng vị trí.\n"
                + " Sau " + soLanDoanToiDa + " lần chơi nếu không tìm ra thì trò chơi sẽ kết thúc.");
    }//GEN-LAST:event_btnGoiYMouseClicked

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        xuLyDoanSo();
    }//GEN-LAST:event_btnOKActionPerformed

    private void tfNhapSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNhapSoActionPerformed
        // TODO add your handling code here:
        xuLyDoanSo();
    }//GEN-LAST:event_tfNhapSoActionPerformed

    private void btnChoiLạiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoiLạiActionPerformed
        // TODO add your handling code here:
        resetTroChoi();
    }//GEN-LAST:event_btnChoiLạiActionPerformed

    public void xuLyDoanSo() {
        int size = arrSoNhap.size();
        if (size < 4) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ 4 chứ số.");
            return;
        }
        if (soLanDoan > soLanDoanToiDa - 1) {
            JOptionPane.showMessageDialog(null, "Lỗi: Số lần đoán vượt quá mức cho phép");
            resetTroChoi();
            return;
        }

        soLanDoan++;
        int soDung = 0;
        int viTriDung = 0;
        String soDoan = "";

        for (int i = 0; i < 4; i++) {
            if (ketQua.indexOf(arrSoNhap.get(i)) != -1) {
                soDung++;
            }

            if (ketQua.get(i) == arrSoNhap.get(i)) {
                viTriDung++;
            }

            soDoan += arrSoNhap.get(i);
        }

      
            
        //xử lý thua
        if (soLanDoan == soLanDoanToiDa && (soDung != 4 || viTriDung != 4)) {
            int xacnhan = JOptionPane.showConfirmDialog(null, "Kết quả là: "+soDoan
                    + "\nBạn có muốn chơi lại không?", "Thua rồi!", 
                    JOptionPane.OK_CANCEL_OPTION);
            if(xacnhan == JOptionPane.OK_OPTION) {
                resetTroChoi();
            }
            else {
                System.exit(0);
            }
            return;
        }
        
        //xử lý thắng
        if(soDung == 4 && viTriDung == 4) {
            int xacnhan = JOptionPane.showConfirmDialog(null, "Chức mừng bạn đã chiến thắng.\nBạn có muốn chơi lại không?", "Xin chức mừng", 
                    JOptionPane.OK_CANCEL_OPTION);
            if(xacnhan == JOptionPane.OK_OPTION) {
                resetTroChoi();
            }
            else {
                System.exit(0);
            }
            return;
        }
                
                
        JPanel pn = new ItemDoanSo(soLanDoan, soDoan, soDung, viTriDung);
        tfNhapSo.setText("");
        arrSoNhap = new ArrayList<>();
        pnListSoDoan.add(pn);
        pnListSoDoan.revalidate();
        pnListSoDoan.repaint();

    }

    public void resetTroChoi() {
        randomKetQua();
        soLanDoan = 0;
        arrSoNhap = new ArrayList<>();
        tfNhapSo.setText("");
        taGhiChu.setText("");
        tfGhiChu1.setText("");
        tfGhiChu2.setText("");
        tfGhiChu3.setText("");
        tfGhiChu4.setText("");
        
        pnListSoDoan.removeAll();
        pnListSoDoan.revalidate();
        pnListSoDoan.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoiLại;
    private javax.swing.JLabel btnGoiY;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnListSoDoan;
    private javax.swing.JTextArea taGhiChu;
    private javax.swing.JTextField tfGhiChu1;
    private javax.swing.JTextField tfGhiChu2;
    private javax.swing.JTextField tfGhiChu3;
    private javax.swing.JTextField tfGhiChu4;
    private javax.swing.JTextField tfNhapSo;
    // End of variables declaration//GEN-END:variables
}
